[package]
name = "engine-audio"
version.workspace = true
edition.workspace = true

[dependencies]
windows = { workspace = true }
crossbeam-channel = { workspace = true }
ringbuf = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
nnnoiseless = { workspace = true }
